[2025-02-08T15:38:58.056759+00:00] database.ERROR: Database connection failed for type Auth {"message":"SQLSTATE[HY000] [1045] Access denied for user 'web'@'localhost' (using password: YES)","type":"Auth","host":"host.docker.internal","dbname":"delight","time":"2025-02-08 15:38:57"} []
[2025-02-08T22:08:44.247624+00:00] database.ERROR: Database connection failed for type Auth {"message":"SQLSTATE[HY000] [1049] Unknown database 'delight2'","type":"Auth","host":"host.docker.internal","dbname":"delight2","time":"2025-02-08 22:08:44"} []
[2025-02-08T22:08:44.582735+00:00] database.ERROR: Database connection failed for type Auth {"message":"SQLSTATE[HY000] [1049] Unknown database 'delight2'","type":"Auth","host":"host.docker.internal","dbname":"delight2","time":"2025-02-08 22:08:44"} []
